apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${NAME}-cis1880-org
spec:
  secretName: ${NAME}-cis1880-org-tls
  dnsNames:
    - "${NAME}.cis1880.org"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
