apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${NAME}-cis188-org
spec:
  secretName: ${NAME}-cis188-org-tls
  dnsNames:
    - "${NAME}.cis188.org"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
